#!/bin/sh

rsync -Lrtvz --exclude=ko.po  translationproject.org::tp/latest/grub/ po-tp.org

autogenerated="en@quot en@hebrew de@hebrew en@cyrillic en@greek en@arabic en@piglatin de_CH"


for x in $autogenerated; do
    rm "po-tp.org/$x.po";
done


(
    (
	cd po-tp.org && ls *.po| cut -d. -f1
	for x in $autogenerated; do
	    echo "$x";
	done
    ) | sort | uniq | xargs
) >po-tp.org/LINGUAS
